project:
  type: website
  output-dir: docs

website:
  title: "Matt Cowgill"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MattCowgill
      - icon: twitter
        href: https://twitter.com/mattcowgill
format:
  html:
    theme: flatly
    mainfont: Roboto
    css: styles.css
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

editor: visual

